<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- saved from url=(0042)http://www.savopropiedades.com.ar/home.php -->
<html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
  <meta http-equiv="content-language" content="es">
  <title>Savo Propiedades - Inmobiliarias Monte Grande - Propiedades - Casas - Departamentos - Chalets - Alquiler y Venta - Lotes</title>
<meta name="description" content="Monte Grande - El Jaguel - Canning - Cañuelas - Ezeiza - Luis Guillón - 9 de Abril - San Pedro - Máximo Paz - Ministro Rivadavia - Alejandro Petión - Spegazzini - Tristán Suárez - Las Toninas - Mar del Tuyú - Departamentos - Casas - Lotes - Cocheras - Casaquintas - Casa dos familias - Locales - Dúplex/Tríplex - Fondos de comercio - Oficinas - Departamentos tipo Casa - Chalets - Para inversionistas - Barrio Cerrado - Inmuebles Comerciales - Campos - Galpones - PH - ">
<meta name="keywords" content="Monte Grande, El Jaguel, Canning, Cañuelas, Ezeiza, Luis Guillón, 9 de Abril, San Pedro, Máximo Paz, Ministro Rivadavia, Alejandro Petión, Spegazzini, Tristán Suárez, Las Toninas, Mar del Tuyú, Departamentos, Casas, Lotes, Cocheras, Casaquintas, Casa dos familias, Locales, Dúplex/Tríplex, Fondos de comercio, Oficinas, Departamentos tipo Casa, Chalets, Para inversionistas, Barrio Cerrado, Inmuebles Comerciales, Campos, Galpones, PH, ">
  <link rel="stylesheet" href="./Savo Propiedades - Inmobiliarias Monte Grande - Propiedades - Casas - Departamentos - Chalets - Alquiler y Venta - Lotes_files/style.css" type="text/css">
    <link rel="stylesheet" href="./Savo Propiedades - Inmobiliarias Monte Grande - Propiedades - Casas - Departamentos - Chalets - Alquiler y Venta - Lotes_files/estilo.css" type="text/css">
  <script type="text/javascript" async="" src="./Savo Propiedades - Inmobiliarias Monte Grande - Propiedades - Casas - Departamentos - Chalets - Alquiler y Venta - Lotes_files/ga.js"></script><script src="./Savo Propiedades - Inmobiliarias Monte Grande - Propiedades - Casas - Departamentos - Chalets - Alquiler y Venta - Lotes_files/AC_RunActiveContent.js" type="text/javascript"></script>
</head>
<body>

  
<meta name="viewport" content="width=device-width,initial-scale=1">

<div id="page">
        <div id="header">
          <div class="wrapper">
            <div id="logo">
              <a href="http://www.savopropiedades.com.ar/"><img src="./Savo Propiedades - Inmobiliarias Monte Grande - Propiedades - Casas - Departamentos - Chalets - Alquiler y Venta - Lotes_files/logo.png" alt="SAVO" title="SAVO" class="logo"></a>
            </div>
            <div class="navbar">
              <a href="http://www.savopropiedades.com.ar/index.html">Home</a><a href="http://www.savopropiedades.com.ar/historia.html">Historia</a><a href="http://www.savopropiedades.com.ar/home.php" class="sel">Propiedades</a><a href="http://www.savopropiedades.com.ar/proyectos.html">Proyectos</a><a href="http://www.savopropiedades.com.ar/contactenos.php">Contacto</a>
            </div>
            <div class="clear"></div>
          </div>
        </div>
        
        <h1 class="highlight">Llamanos al 4296-8543<br>y a la brevedad responderemos todas tus dudas.</h1>
        <div class="clear"></div>
        
        <div id="main">
          <div class="wrapper">
            <div class="content">
              <div class="hr_white"></div><center>
<table class="panel" cellspacing="0">
  <tbody><tr>
    <td class="panel_1" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=20" class="panel" title="Propiedades en 9 de Abril">9 de Abril [1]</a></td>
    <td class="panel_2" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=17" class="panel" title="Propiedades en Canning">Canning [4]</a></td>
    <td class="panel_3" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=449" class="panel" title="Propiedades en Canning">Canning [1]</a></td>
  </tr>
  <tr>
    <td class="panel_1" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=39" class="panel" title="Propiedades en El Jaguel">El Jaguel [1]</a></td>
    <td class="panel_2" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=62" class="panel" title="Propiedades en Las Toninas">Las Toninas [1]</a></td>
    <td class="panel_3" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=18" class="panel" title="Propiedades en Luis Guillón">Luis Guillón [4]</a></td>
  </tr>
  <tr>
    <td class="panel_1" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=50" class="panel" title="Propiedades en Mar del Tuyú">Mar del Tuyú [2]</a></td>
    <td class="panel_2" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=97" class="panel" title="Propiedades en Máximo Paz">Máximo Paz [1]</a></td>
    <td class="panel_3" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=154" class="panel" title="Propiedades en Ministro Rivadavia">Ministro Rivadavia [2]</a></td>
  </tr>
  <tr>
    <td class="panel_1" nowrap=""><a href="http://www.savopropiedades.com.ar/listado.php?localidad_id=19" class="panel" title="Propiedades en Monte Grande">Monte Grande [58]</a></td>
    <td class="panel_2">&nbsp;</td>
    <td class="panel_3">&nbsp;</td>
  </tr>
</tbody></table>
</center>
              <div class="clear"></div>
            </div>
            <div class="clear"></div>
          </div>
        </div>
        <div class="push"></div>
      </div>
      <div id="footer">
        <div class="wrapper">
          <div class="contfooter">
          
            <ul class="col">
              <li class="col220">
                <h3>Dirección</h3>
                <p> Hipólito Yrigoyen 243 - Planta Baja</p>
              </li>
              <li class="col220">
                <h3>Teléfono</h3>
                <p>4296-8543</p>
                <ul class="social">
                  <li><a href="http://www.savopropiedades.com.ar/home.php#"></a></li>
                </ul>
              </li>
              <li class="col220">
                <h3>Social</h3>
                <p> <a href="http://www.savopropiedades.com.ar/home.php#"><img src="./Savo Propiedades - Inmobiliarias Monte Grande - Propiedades - Casas - Departamentos - Chalets - Alquiler y Venta - Lotes_files/ico_facebook.png" alt="Facebook" title="Facebook"></a><a href="http://www.savopropiedades.com.ar/blog.html"></a></p>
              </li>
              <li class="col220">
                <h3>Diseño Vip</h3>
                <p>Diseño y programación <a href="http://www.xn--diseovip-g3a.com.ar/" target="_blank">www.diseñovip.com.ar</a></p>
              </li>
            </ul>
            
            <div class="clear"></div>
            <div class="hr_black"></div>
            
            <p>2012 © <a href="http://www.savopropiedades.com.ar/index.html">SAVO PROPIEDADES</a> Todos los derechos reservados.</p>
          
          </div>
        </div>
      </div>
    

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18165944-40']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>


</body></html>